# Training-Specific Configuration

experiment:
  name: "silver_baseline_v1"
  # TODO: Configure experiment tracking
  track_metrics: true
  save_checkpoints: true
  checkpoint_frequency: 5

optimizer:
  # TODO: Configure optimizer settings
  type: "AdamW"
  learning_rate: 0.001
  weight_decay: 0.0001
  betas: [0.9, 0.999]

scheduler:
  # TODO: Configure learning rate scheduler
  type: "ReduceLROnPlateau"
  factor: 0.5
  patience: 5
  min_lr: 0.00001

# TODO: Configure data augmentation
augmentation:
  enabled: false
  techniques: []

# TODO: Configure regularization
regularization:
  dropout: 0.2
  layer_norm: true
  gradient_clipping: 1.0
